# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f54ab157ef54c68285c882b9c93462d"
name = "Price Watch"
application_url = "https://zixsw7530bseuso30tid1xpp.217.160.121.83.sslip.io"
embedded = true

[access_scopes]
scopes = "read_products"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = ["app/scopes_update"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/upsert"
  topics = ["products/create", "products/update"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/delete"
  topics = ["products/delete"]

[auth]
redirect_urls = ["https://zixsw7530bseuso30tid1xpp.217.160.121.83.sslip.io/api/auth"]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
